# AutoEncodeServer Config Template (v3.5)
---

MaxNumberOfJobsInQueue: 30
HoursCompletedUntilRemoval: 1
HoursErroredUntilRemoval: 2
VideoFileExtensions: ['.mkv', '.m4v', '.avi']
SecondarySkipExtension: 'skip'

Ffmpeg:
    FfmpegDirectory: '\\ffmpeg\dir'
    FfprobeDirectory: '\\ffprobe\dir'

Hdr10Plus:
    Enabled: True
    Hdr10PlusToolFullPath: '\\path\to\hdr10plus_tool'

DolbyVision:
    Enabled: True
    DoviToolFullPath: '\\path\to\dovi_tool'
    X265FullPath: '\\path\to\x265'
    MkvMergeFullPath: '\\path\to\mkvmerge'

Logger:
    LogFileDirectory: ''
    MaxFileSizeInBytes: 102400
    BackupFileCount: 3

Connection:
    ClientUpdatePort: 39000
    CommunicationPort: 39001

Directories:
    Movies:
        Source: '\\Source\Path\Movies'
        Destination: '\\Destination\Path\Movies (Encoded)'
        Automated: True
        EpisodeNaming: False
        PostProcessing:
            CopyFilePaths: ['\\Fake\Path1', '\\Path\Fake2']
            DeleteSourceFile: False

    TV Shows:
        Source: '\\Source\Path\TV Shows'
        Destination: '\\Source\Path\TV Shows (Encoded)'
        Automated: False
        EpisodeNaming: True
