# AutoEncodeServer Config Template
---

FFmpegDirectory: ''
X265FullPath: ''
HDR10PlusExtractorFullPath: ''
DolbyVisionExtractorFullPath: ''
DolbyVisionEncodingEnabled: True
MkvMergeFullPath: ''
MaxNumberOfJobsInQueue: 30
HoursCompletedUntilRemoval: 1
HoursErroredUntilRemoval: 2
VideoFileExtensions: ['.mkv', '.m4v', '.avi']
SecondarySkipExtension: 'skip'

LoggerSettings:
    LogFileLocation: ''
    MaxFileSizeInBytes: 102400
    BackupFileCount: 3

ConnectionSettings:
    IPAddress: '127.0.0.1'  # Unused by server
    ClientUpdatePort: 39000
    CommunicationPort: 39001

Directories:
    Movies:
        Source: '\\Source\Path\Movies'
        Destination: '\\Destination\Path\Movies (Encoded)'
        Automated: True
        EpisodeNaming: False
        PostProcessing:
            CopyFilePaths: ['\\Fake\Path1', '\\Path\Fake2']
            DeleteSourceFile: False

    TV Shows:
        Source: '\\Source\Path\TV Shows'
        Destination: '\\Source\Path\TV Shows (Encoded)'
        Automated: False
        EpisodeNaming: True
