# AutomatedFFmpegServer Config Template
---
ServerSettings:
    IP: 127.0.0.1
    Port: 39000
    VideoFileExtensions: ['.mkv', '.m4v', '.avi']
    ThreadSleepInMS: 300000
    FFmpegDirectory: ''
    HDR10PlusExtractorFullPath: ''
    DolbyVisionExtractorFullPath: ''
    LoggerSettings:
        LogFileLocation: '\Fake\Path'
        MaxFileSizeInBytes: 4098
        BackupFileCount: 3

GlobalJobSettings:
    MaxNumberOfJobsInQueue: 20
    HoursCompletedUntilRemoval: 1
    HoursErroredUntilRemoval: 2

Directories:
    Movies:
        Source: '\\Source\Path\Movies'
        Destination: '\\Destination\Path\Movies (Encoded)'
        Automated: True
        TVShowStructure: False
        PostProcessing:
            CopyFilePaths: ['\\Fake\Path1', '\\Path\Fake2']
            DeleteSourceFile: False

    TV Shows:
        Source: '\\Source\Path\TV Shows'
        Destination: '\\Source\Path\TV Shows (Encoded)'
        Automated: False
        TVShowStructure: True
