# Automated FFmpeg Server Config
---
ServerSettings:
    IP: 127.0.0.1
    Port: 39000
    VideoFileExtensions: ['.mkv', '.m4v', '.avi']
    ThreadSleepInMS: 300000
    FFmpegDirectory: ''
    LoggerSettings:
        LogFileLocation: '\Fake\Path'
        MaxFileSizeInBytes: 4098
        BackupFileCount: 3

Directories:
    Movies:
        Source: '\\Source\Path\Movies'
        Destination: '\\Destination\Path\Movies (Encoded)'
        Automated: True
        TVShowStructure: False

    TV Shows:
        Source: '\\Source\Path\TV Shows'
        Destination: '\\Source\Path\TV Shows (Encoded)'
        Automated: False
        TVShowStructure: True
